/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Star_Cinemas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jacob.s
 */
public class BillingPanel extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public BillingPanel() {
        initComponents();
        billingPanel();
        getCategory();
    }

    Database db = new Database();
    Connection conn = null;
    Statement statement = null;
    ResultSet resultSet = null;
    ResultSet movieResultSet = null;

    String url = "jdbc:derby://localhost:1527/StarCinemasDB";
    String usernameDerby = "Jacob";
    String passwordDerby = "1234";

    Random rand = new Random(); //instance of random class
    int upperbound = 250000;
    //generate random values from 0-250,000

    double billingPrice = 0.0;
    double ticketBillingPrice = 0.0;
    double billTotal = 0.0;
    double ticketBillTotal = 0.0;
    double finalTotal = 0.0;
    double ticketFinalTotal = 0.0;
    int i;
    int availableQuantity;
    int ticketAvailableQuantity;
    int productNumber;
    int movieNumber;
    int updatedQuantityCount;
    int updatedTicketCount;

    public void billingPanel() {
        try
        {
            /*
            Initializes a database connection to output all products & movies from product & movie table via 
            resultSet in table form using rs2xml. 
             */
            //conn = DriverManager.getConnection(url, usernameDerby, passwordDerby);
            conn = db.establishConnection();
            statement = conn.createStatement();
            resultSet = statement.executeQuery("Select * from " + usernameDerby + ".PRODUCTTABLE");
            productTable.setModel(DbUtils.resultSetToTableModel(resultSet));
            movieResultSet = statement.executeQuery("Select * from " + usernameDerby + ".MOVIETABLE");
            movieTable.setModel(DbUtils.resultSetToTableModel(movieResultSet));

        } catch (SQLException ex)
        {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getCategory() {
        try
        {
            /*
            Initializes a database connection to output all categories from category table for filter request.
             */
            //conn = DriverManager.getConnection(url, usernameDerby, passwordDerby);
            conn = db.establishConnection();
            statement = conn.createStatement();
            resultSet = statement.executeQuery("Select * from JACOB.CATEGORYTABLE");

            while (resultSet.next())
            {
                String categories = resultSet.getString("CATEGORYNAME");
                productCategory.addItem(categories);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitProduct = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        productPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        productCategory = new javax.swing.JComboBox<>();
        refreshBill = new javax.swing.JButton();
        clearBill = new javax.swing.JButton();
        printBill = new javax.swing.JButton();
        addToBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billingText = new javax.swing.JTextArea();
        finalTotalDisplay = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        filterResults = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        movieName = new javax.swing.JTextField();
        ticketQuantity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addTicketToBill = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        employeePanelJump = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        categoryPanelJump = new javax.swing.JLabel();
        logoutPanelJump = new javax.swing.JLabel();
        productPanelJump = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 48, 215));

        exitProduct.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        exitProduct.setForeground(new java.awt.Color(255, 153, 204));
        exitProduct.setText("X");
        exitProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitProductMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Oriya MN", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 204));
        jLabel2.setText("Star Cinemas");

        jLabel4.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 204));
        jLabel4.setText("Billing Point");

        customerName.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 204));
        jLabel3.setText("Customer Full Name");

        productName.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 204));
        jLabel5.setText("Product Name");

        productQuantity.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        productQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productQuantityActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 204));
        jLabel7.setText("Quantity");

        productPrice.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        productPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productPriceMouseClicked(evt);
            }
        });
        productPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPriceActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 204));
        jLabel8.setText("Price");

        productCategory.setFont(new java.awt.Font("Oriya MN", 0, 14)); // NOI18N
        productCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productCategoryMouseClicked(evt);
            }
        });
        productCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCategoryActionPerformed(evt);
            }
        });

        refreshBill.setBackground(new java.awt.Color(18, 30, 49));
        refreshBill.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        refreshBill.setForeground(new java.awt.Color(255, 153, 204));
        refreshBill.setText("Refresh");
        refreshBill.setToolTipText("");
        refreshBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBillMouseClicked(evt);
            }
        });
        refreshBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBillActionPerformed(evt);
            }
        });

        clearBill.setBackground(new java.awt.Color(18, 30, 49));
        clearBill.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        clearBill.setForeground(new java.awt.Color(255, 153, 204));
        clearBill.setText("Clear");
        clearBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBillMouseClicked(evt);
            }
        });
        clearBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBillActionPerformed(evt);
            }
        });

        printBill.setBackground(new java.awt.Color(18, 30, 49));
        printBill.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        printBill.setForeground(new java.awt.Color(255, 153, 204));
        printBill.setText("Print");
        printBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBillMouseClicked(evt);
            }
        });
        printBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBillActionPerformed(evt);
            }
        });

        addToBill.setBackground(new java.awt.Color(18, 30, 49));
        addToBill.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        addToBill.setForeground(new java.awt.Color(255, 153, 204));
        addToBill.setText("Add");
        addToBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToBillMouseClicked(evt);
            }
        });
        addToBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToBillActionPerformed(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "productID", "Name", "Quantity", "Price", "Category"
            }
        ));
        productTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        productTable.setRowHeight(50);
        productTable.setSelectionBackground(new java.awt.Color(255, 153, 204));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        jLabel6.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 204));
        jLabel6.setText("Details");

        jLabel10.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 204));
        jLabel10.setText("List of Products");

        billingText.setColumns(20);
        billingText.setRows(5);
        jScrollPane2.setViewportView(billingText);

        finalTotalDisplay.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        finalTotalDisplay.setForeground(new java.awt.Color(255, 153, 204));
        finalTotalDisplay.setText("Total $:");

        jLabel12.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 204));
        jLabel12.setText("Checkout");

        filterResults.setBackground(new java.awt.Color(18, 30, 49));
        filterResults.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        filterResults.setForeground(new java.awt.Color(255, 153, 204));
        filterResults.setText("Filter");
        filterResults.setToolTipText("");
        filterResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterResultsMouseClicked(evt);
            }
        });
        filterResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterResultsActionPerformed(evt);
            }
        });

        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MovieID", "Genre", "Name", "Duration", "Date", "Session", "Actors", "Director", "Quantity", "Price"
            }
        ));
        movieTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        movieTable.setRowHeight(50);
        movieTable.setSelectionBackground(new java.awt.Color(255, 153, 204));
        movieTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(movieTable);

        jLabel11.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 204));
        jLabel11.setText("List of Movies");

        jLabel9.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 204));
        jLabel9.setText("Movie Name");

        movieName.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        movieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieNameActionPerformed(evt);
            }
        });

        ticketQuantity.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        ticketQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketQuantityActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 204));
        jLabel13.setText("Ticket Quantity");

        addTicketToBill.setBackground(new java.awt.Color(18, 30, 49));
        addTicketToBill.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        addTicketToBill.setForeground(new java.awt.Color(255, 153, 204));
        addTicketToBill.setText("Add");
        addTicketToBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTicketToBillMouseClicked(evt);
            }
        });
        addTicketToBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTicketToBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(375, 375, 375)
                .addComponent(exitProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(finalTotalDisplay)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ticketQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(153, 153, 153)
                        .addComponent(addToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBill, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearBill, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(849, 849, 849)
                        .addComponent(filterResults)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printBill, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTicketToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(exitProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticketQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(filterResults)
                            .addComponent(productCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addTicketToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(finalTotalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 990));

        employeePanelJump.setFont(new java.awt.Font("Oriya MN", 1, 36)); // NOI18N
        employeePanelJump.setForeground(new java.awt.Color(102, 48, 215));
        employeePanelJump.setText("Employees");
        employeePanelJump.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeePanelJumpMouseClicked(evt);
            }
        });

        Menu.setFont(new java.awt.Font("Oriya MN", 1, 36)); // NOI18N
        Menu.setForeground(new java.awt.Color(102, 48, 215));
        Menu.setText("Menu");

        categoryPanelJump.setFont(new java.awt.Font("Oriya MN", 1, 36)); // NOI18N
        categoryPanelJump.setForeground(new java.awt.Color(102, 48, 215));
        categoryPanelJump.setText("Categories");
        categoryPanelJump.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryPanelJumpMouseClicked(evt);
            }
        });

        logoutPanelJump.setFont(new java.awt.Font("Oriya MN", 1, 36)); // NOI18N
        logoutPanelJump.setForeground(new java.awt.Color(102, 48, 215));
        logoutPanelJump.setText("Log out");
        logoutPanelJump.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelJumpMouseClicked(evt);
            }
        });

        productPanelJump.setFont(new java.awt.Font("Oriya MN", 1, 36)); // NOI18N
        productPanelJump.setForeground(new java.awt.Color(102, 48, 215));
        productPanelJump.setText("Products");
        productPanelJump.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productPanelJumpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(employeePanelJump)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(Menu))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(categoryPanelJump))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(productPanelJump))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(logoutPanelJump)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(Menu)
                .addGap(166, 166, 166)
                .addComponent(productPanelJump)
                .addGap(26, 26, 26)
                .addComponent(categoryPanelJump)
                .addGap(30, 30, 30)
                .addComponent(employeePanelJump)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutPanelJump)
                .addGap(237, 237, 237))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameActionPerformed

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    private void productQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productQuantityActionPerformed

    private void productCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productCategoryActionPerformed

    private void refreshBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshBillActionPerformed

    private void clearBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBillActionPerformed

    private void printBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printBillActionPerformed

    private void addToBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToBillActionPerformed

    private void refreshBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBillMouseClicked
        // TODO add your handling code here:
        billingPanel();

    }//GEN-LAST:event_refreshBillMouseClicked

    private void clearBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBillMouseClicked
        // TODO add your handling code here:

        customerName.setText("");
        productName.setText("");
        productQuantity.setText("");
        productPrice.setText("");
        //productPrice.setText("");
    }//GEN-LAST:event_clearBillMouseClicked

    public void ticketQuantityUpdate() {
        try
        {
            //conn = DriverManager.getConnection(url, usernameDerby, passwordDerby);
            conn = db.establishConnection();
            String editQuery = "Update JACOB.MOVIETABLE set QUANTITY=" + updatedTicketCount + "" + "where MOVIEID=" + movieNumber;
            Statement edit = conn.createStatement();
            edit.executeUpdate(editQuery);
            billingPanel();

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    public void quantityUpdate() {
        try
        {
            //conn = DriverManager.getConnection(url, usernameDerby, passwordDerby);
            conn = db.establishConnection();
            String editQuery = "Update JACOB.PRODUCTTABLE set PRODUCTQUANTITY=" + updatedQuantityCount + "" + "where PRODUCTID=" + productNumber;
            Statement edit = conn.createStatement();
            edit.executeUpdate(editQuery);
            billingPanel();

        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    private void addToBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToBillMouseClicked
        // TODO add your handling code here:
        if (productName.getText().isEmpty() || productQuantity.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information!");
        } else if (availableQuantity <= Integer.valueOf(productQuantity.getText()))
        {
            JOptionPane.showMessageDialog(this, "Out of stock");
        } else
        {
            int randomBillGenerator = rand.nextInt(upperbound);
            //productID.setText() = randomBillGenerator;
            i++;
            billTotal = billingPrice * Double.valueOf(productQuantity.getText());
            finalTotal = finalTotal + billTotal;
            if (i == 1)
            {
                billingText.setText(billingText.getText() + "\t----------Checkout----------\n"
                        + "Num        Product            Price       Quantity        Total\n" + i
                        + "             " + productName.getText() + "        " + billingPrice + "              " + productQuantity.getText() + "             "
                        + billTotal + "\n");
            } else
            {
                billingText.setText(billingText.getText() + i
                        + "             " + productName.getText() + "        " + billingPrice + "              " + productQuantity.getText() + "             "
                        + billTotal + "\n");
            }
            finalTotalDisplay.setText("Total $:" + (finalTotal + ticketFinalTotal));

            updatedQuantityCount -= Integer.valueOf(productQuantity.getText());
            quantityUpdate();
        }
    }//GEN-LAST:event_addToBillMouseClicked

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        int tableSelection = productTable.getSelectedRow();

        productName.setText(model.getValueAt(tableSelection, 1).toString());
        productPrice.setText(model.getValueAt(tableSelection, 3).toString());
        productCategory.setSelectedItem(model.getValueAt(tableSelection, 4).toString());
        billingPrice = Double.valueOf(model.getValueAt(tableSelection, 3).toString());
        //billTotal = billingPrice * Double.parseDouble(productQuantity.getText());
        productNumber = Integer.valueOf(model.getValueAt(tableSelection, 0).toString());
        availableQuantity = Integer.valueOf(model.getValueAt(tableSelection, 2).toString());
        updatedQuantityCount = availableQuantity;

        //productPrice.setText(model.getValueAt(tableSelection, 3).toString());
    }//GEN-LAST:event_productTableMouseClicked

    private void printBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBillMouseClicked
        // TODO add your handling code here:
        try
        {
            billingText.print();
        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_printBillMouseClicked

    private void exitProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitProductMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitProductMouseClicked

    private void employeePanelJumpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePanelJumpMouseClicked
        // TODO add your handling code here:
        new Employee().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employeePanelJumpMouseClicked

    private void categoryPanelJumpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryPanelJumpMouseClicked
        // TODO add your handling code here:
        new Category().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_categoryPanelJumpMouseClicked

    private void logoutPanelJumpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelJumpMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutPanelJumpMouseClicked

    private void productPanelJumpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productPanelJumpMouseClicked
        // TODO add your handling code here:
        new Products().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productPanelJumpMouseClicked

    private void productCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productCategoryMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_productCategoryMouseClicked

    private void filterResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterResultsMouseClicked
        // TODO add your handling code here:
        try
        {
            //conn = DriverManager.getConnection(url, usernameDerby, passwordDerby);
            conn = db.establishConnection();
            statement = conn.createStatement();
            resultSet = statement.executeQuery("Select * from " + usernameDerby + ".PRODUCTTABLE where PRODUCTCATEGORY='" + productCategory.getSelectedItem().toString() + "'");
            productTable.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (SQLException ex)
        {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_filterResultsMouseClicked

    private void filterResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterResultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterResultsActionPerformed

    private void movieTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) movieTable.getModel();
        int tableSelection = movieTable.getSelectedRow();

        movieName.setText(model.getValueAt(tableSelection, 2).toString());
        //ticketQuantity.setText(model.getValueAt(tableSelection, 4).toString());
        ticketBillingPrice = Double.valueOf(model.getValueAt(tableSelection, 9).toString());
        //billTotal = billingPrice * Double.parseDouble(productQuantity.getText());
        movieNumber = Integer.valueOf(model.getValueAt(tableSelection, 0).toString());
        ticketAvailableQuantity = Integer.valueOf(model.getValueAt(tableSelection, 8).toString());
        updatedTicketCount = ticketAvailableQuantity;

    }//GEN-LAST:event_movieTableMouseClicked

    private void movieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieNameActionPerformed

    private void ticketQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketQuantityActionPerformed

    private void addTicketToBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTicketToBillMouseClicked
        // TODO add your handling code here:
        if (movieName.getText().isEmpty() || ticketQuantity.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information!");
        } else if (ticketAvailableQuantity <= Integer.valueOf(ticketQuantity.getText()))
        {
            JOptionPane.showMessageDialog(this, "Out of stock");
        } else
        {
            i++;
            ticketBillTotal = ticketBillingPrice * Double.valueOf(ticketQuantity.getText());
            ticketFinalTotal = ticketFinalTotal + ticketBillTotal;
            if (i == 1)
            {
                billingText.setText(billingText.getText() + "\t----------Movie Tickets----------\n"
                        + "Num        Movie            Price       Quantity        Total\n" + i
                        + "             " + movieName.getText() + "        " + ticketBillingPrice + "              " + ticketQuantity.getText() + "             "
                        + ticketBillTotal + "\n");
            } else
            {
                billingText.setText(billingText.getText() + i
                        + "             " + movieName.getText() + "        " + ticketBillingPrice + "              " + ticketQuantity.getText() + "             "
                        + ticketBillTotal + "\n");
            }
            finalTotalDisplay.setText("Total $:" + (finalTotal + ticketFinalTotal));

            updatedTicketCount -= Integer.valueOf(ticketQuantity.getText());
            ticketQuantityUpdate();
        }
    }//GEN-LAST:event_addTicketToBillMouseClicked

    private void addTicketToBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTicketToBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTicketToBillActionPerformed

    private void productPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceActionPerformed

    private void productPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productPriceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BillingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BillingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BillingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BillingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JButton addTicketToBill;
    private javax.swing.JButton addToBill;
    private javax.swing.JTextArea billingText;
    private javax.swing.JLabel categoryPanelJump;
    private javax.swing.JButton clearBill;
    private javax.swing.JTextField customerName;
    private javax.swing.JLabel employeePanelJump;
    private javax.swing.JLabel exitProduct;
    private javax.swing.JButton filterResults;
    private javax.swing.JLabel finalTotalDisplay;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logoutPanelJump;
    private javax.swing.JTextField movieName;
    private javax.swing.JTable movieTable;
    private javax.swing.JButton printBill;
    private javax.swing.JComboBox<String> productCategory;
    private javax.swing.JTextField productName;
    private javax.swing.JLabel productPanelJump;
    private javax.swing.JTextField productPrice;
    private javax.swing.JTextField productQuantity;
    private javax.swing.JTable productTable;
    private javax.swing.JButton refreshBill;
    private javax.swing.JTextField ticketQuantity;
    // End of variables declaration//GEN-END:variables
}
