/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Star_Cinemas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jacob.s
 */
public class MoviePanel extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public MoviePanel() {
        initComponents();
        selectMovie();
    }

    Database db = new Database();

    Connection conn = null;
    Statement statement = null;
    ResultSet resultSet = null;

    String url = "jdbc:derby://localhost:1527/StarCinemasDB";
    String usernameDerby = "Jacob";
    String passwordDerby = "1234";

    public void selectMovie() {
        try
        {
            /*
            Initializes a database connection to output all movies from movie table via 
            resultSet in table form using rs2xml. 
             */
            conn = db.establishConnection();
            //conn = DriverManager.getConnection(url, usernameDerby, passwordDerby);
            statement = conn.createStatement();
            resultSet = statement.executeQuery("Select * from " + usernameDerby + ".MOVIETABLE");
            movieTable.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (SQLException ex)
        {
            Logger.getLogger(MoviePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        employeePanelJump = new javax.swing.JLabel();
        categoryPanelJump = new javax.swing.JLabel();
        logoutPanelJump = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        exitProduct = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        movieID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        movieName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        movieTicketQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        moviePrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        movieCategory = new javax.swing.JComboBox<>();
        addMovie = new javax.swing.JButton();
        clearMovie = new javax.swing.JButton();
        editMovie = new javax.swing.JButton();
        deleteMovie = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        movieDesc = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));

        Menu.setFont(new java.awt.Font("Oriya MN", 1, 36)); // NOI18N
        Menu.setForeground(new java.awt.Color(102, 48, 215));
        Menu.setText("Menu");

        employeePanelJump.setFont(new java.awt.Font("Oriya MN", 1, 36)); // NOI18N
        employeePanelJump.setForeground(new java.awt.Color(102, 48, 215));
        employeePanelJump.setText("Employees");
        employeePanelJump.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeePanelJumpMouseClicked(evt);
            }
        });

        categoryPanelJump.setFont(new java.awt.Font("Oriya MN", 1, 36)); // NOI18N
        categoryPanelJump.setForeground(new java.awt.Color(102, 48, 215));
        categoryPanelJump.setText("Categories");
        categoryPanelJump.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryPanelJumpMouseClicked(evt);
            }
        });

        logoutPanelJump.setFont(new java.awt.Font("Oriya MN", 1, 36)); // NOI18N
        logoutPanelJump.setForeground(new java.awt.Color(102, 48, 215));
        logoutPanelJump.setText("Log out");
        logoutPanelJump.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelJumpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(Menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(categoryPanelJump)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logoutPanelJump)
                        .addGap(51, 51, 51))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(employeePanelJump)
                    .addGap(16, 16, 16)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(Menu)
                .addGap(161, 161, 161)
                .addComponent(categoryPanelJump)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutPanelJump)
                .addGap(156, 156, 156))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(222, 222, 222)
                    .addComponent(employeePanelJump)
                    .addContainerGap(723, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(102, 48, 215));
        jPanel1.setPreferredSize(new java.awt.Dimension(919, 990));

        exitProduct.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        exitProduct.setForeground(new java.awt.Color(255, 153, 204));
        exitProduct.setText("X");
        exitProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitProductMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Oriya MN", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 204));
        jLabel2.setText("Star Cinemas");

        jLabel4.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 204));
        jLabel4.setText("Manage Movies");

        movieID.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        movieID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 204));
        jLabel3.setText("MovieID");

        movieName.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        movieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 204));
        jLabel5.setText("Name");

        movieTicketQuantity.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        movieTicketQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieTicketQuantityActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 204));
        jLabel7.setText("Quantity");

        moviePrice.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        moviePrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moviePriceMouseClicked(evt);
            }
        });
        moviePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviePriceActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 204));
        jLabel8.setText("Price");

        jLabel9.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 204));
        jLabel9.setText("Category");

        movieCategory.setFont(new java.awt.Font("Oriya MN", 0, 14)); // NOI18N
        movieCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adventure", "Action ", "Animation", "Comedy ", "Crime", "Drama ", "Fantasy ", "Mystery", "Horror ", "Romance ", "Sci-Fi", "Sport", "SuperHero", "War", "Western ", "Thriller " }));
        movieCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieCategoryActionPerformed(evt);
            }
        });

        addMovie.setBackground(new java.awt.Color(18, 30, 49));
        addMovie.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        addMovie.setForeground(new java.awt.Color(255, 153, 204));
        addMovie.setText("Add");
        addMovie.setToolTipText("");
        addMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMovieMouseClicked(evt);
            }
        });
        addMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieActionPerformed(evt);
            }
        });

        clearMovie.setBackground(new java.awt.Color(18, 30, 49));
        clearMovie.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        clearMovie.setForeground(new java.awt.Color(255, 153, 204));
        clearMovie.setText("Clear");
        clearMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMovieMouseClicked(evt);
            }
        });
        clearMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMovieActionPerformed(evt);
            }
        });

        editMovie.setBackground(new java.awt.Color(18, 30, 49));
        editMovie.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        editMovie.setForeground(new java.awt.Color(255, 153, 204));
        editMovie.setText("Edit");
        editMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMovieMouseClicked(evt);
            }
        });
        editMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMovieActionPerformed(evt);
            }
        });

        deleteMovie.setBackground(new java.awt.Color(18, 30, 49));
        deleteMovie.setFont(new java.awt.Font("Oriya MN", 1, 24)); // NOI18N
        deleteMovie.setForeground(new java.awt.Color(255, 153, 204));
        deleteMovie.setText("Delete");
        deleteMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMovieMouseClicked(evt);
            }
        });
        deleteMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMovieActionPerformed(evt);
            }
        });

        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MovieID", "Name", "Description", "Quantity", "Price", "Category"
            }
        ));
        movieTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        movieTable.setRowHeight(50);
        movieTable.setSelectionBackground(new java.awt.Color(255, 153, 204));
        movieTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(movieTable);

        jLabel6.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 204));
        jLabel6.setText("Description");

        movieDesc.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        movieDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(31, 31, 31)
                        .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(movieID, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(31, 31, 31)
                        .addComponent(movieDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(385, 385, 385))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(271, 271, 271)
                        .addComponent(exitProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(deleteMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(clearMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movieTicketQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(394, 394, 394)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(moviePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(movieCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moviePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movieTicketQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(movieCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(movieDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void movieIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieIDActionPerformed

    private void movieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieNameActionPerformed

    private void movieTicketQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieTicketQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieTicketQuantityActionPerformed

    private void moviePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moviePriceActionPerformed

    private void movieCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieCategoryActionPerformed

    private void addMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMovieActionPerformed

    private void clearMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMovieActionPerformed

    private void editMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMovieActionPerformed

    private void deleteMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMovieActionPerformed

    private void addMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMovieMouseClicked
        // TODO add your handling code here:

        if (movieID.getText().isEmpty() || movieName.getText().isEmpty() || movieDesc.getText().isEmpty() || movieTicketQuantity.getText().isEmpty()
                || moviePrice.getText().isEmpty() || movieCategory.getSelectedItem().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Movie Missing Information!");
        } else
        {
            try
            {
                //conn = DriverManager.getConnection(url, usernameDerby, passwordDerby);
                conn = db.establishConnection();
                PreparedStatement add = conn.prepareStatement("insert into MOVIETABLE values(?, ?, ?, ?, ?, ?)");

                add.setInt(1, Integer.valueOf(movieID.getText()));
                add.setString(2, movieName.getText().trim());
                add.setString(3, movieDesc.getText().trim());
                add.setDouble(4, Double.parseDouble(moviePrice.getText()));
                add.setInt(5, Integer.parseInt(movieTicketQuantity.getText()));
                add.setString(6, movieCategory.getSelectedItem().toString());
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Movie Successfully Added!");
                System.out.println("Movie Added!");
                conn.close();
                selectMovie();

            } catch (SQLException ex)
            {
                if (ex.getSQLState().startsWith("23"))
                {
                    JOptionPane.showMessageDialog(this, "Duplicate ID Exists, Enter Unique ID!");
                } else
                {
                    Logger.getLogger(MoviePanel.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Invalid Input!\n"
                        + "ID = Whole Numbers only\n"
                        + "Name = All characters\n"
                        + "Description = All characters\n"
                        + "Price = All numbers\n"
                        + "Quantity = Whole Numbers only\n");
            }
        }
    }//GEN-LAST:event_addMovieMouseClicked

    private void moviePriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviePriceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moviePriceMouseClicked

    private void clearMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMovieMouseClicked
        // TODO add your handling code here:

        movieID.setText("");
        movieName.setText("");
        movieDesc.setText("");
        moviePrice.setText("");
        movieTicketQuantity.setText("");
    }//GEN-LAST:event_clearMovieMouseClicked

    private void deleteMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMovieMouseClicked
        // TODO add your handling code here:
        if (movieID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Select Movie to be Deleted!");
        } else
        {
            try
            {
                //conn = DriverManager.getConnection(url, usernameDerby, passwordDerby);
                conn = db.establishConnection();
                String movieSelection = movieID.getText();
                String deleteQuery = "Delete from JACOB.MOVIETABLE where MOVIEID=" + movieSelection;
                Statement delete = conn.createStatement();
                delete.executeUpdate(deleteQuery);
                selectMovie();
                JOptionPane.showMessageDialog(this, "Selected Movie Deleted!");

            } catch (Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_deleteMovieMouseClicked

    private void movieTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) movieTable.getModel();
        int tableSelection = movieTable.getSelectedRow();
        movieID.setText(model.getValueAt(tableSelection, 0).toString());
        movieName.setText(model.getValueAt(tableSelection, 1).toString());
        movieDesc.setText(model.getValueAt(tableSelection, 2).toString());
        moviePrice.setText(model.getValueAt(tableSelection, 3).toString());
        movieTicketQuantity.setText(model.getValueAt(tableSelection, 4).toString());
        movieCategory.setSelectedItem(model.getValueAt(tableSelection, 5).toString());
    }//GEN-LAST:event_movieTableMouseClicked

    private void editMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMovieMouseClicked
        // TODO add your handling code here:
        if (movieID.getText().isEmpty() || movieName.getText().isEmpty() || movieDesc.getText().isEmpty() || movieTicketQuantity.getText().isEmpty()
                || moviePrice.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Movie Missing Information!");
        } else
        {
            try
            {
                //conn = DriverManager.getConnection(url, usernameDerby, passwordDerby);
                conn = db.establishConnection();
                String editQuery = "Update JACOB.MOVIETABLE set MOVIENAME='" + movieName.getText().trim() + "'" + ",MOVIEDESC='" + movieDesc.getText().trim() + "'" + ",MOVIEPRICE=" + Double.parseDouble(moviePrice.getText()) + "" + ",MOVIEQUANTITY=" + Integer.parseInt(movieTicketQuantity.getText()) + "" + ",MOVIECATEGORY='" + movieCategory.getSelectedItem().toString() + "'" + "where MOVIEID=" + movieID.getText();
                Statement edit = conn.createStatement();
                edit.executeUpdate(editQuery);
                JOptionPane.showMessageDialog(this, "Selected Movie Edited!");
                selectMovie();

            } catch (SQLException ex)
            {
                if (ex.getSQLState().startsWith("23"))
                {
                    JOptionPane.showMessageDialog(this, "Duplicate ID Exists, Enter Unique ID!");
                } else
                {
                    Logger.getLogger(MoviePanel.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Invalid Input!\n"
                        + "ID = Whole Numbers only\n"
                        + "Name = All characters\n"
                        + "Description = All characters\n"
                        + "Price = All numbers\n"
                        + "Quantity = Whole Numbers only\n");
            }
        }
    }//GEN-LAST:event_editMovieMouseClicked

    private void exitProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitProductMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitProductMouseClicked

    private void employeePanelJumpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePanelJumpMouseClicked
        // TODO add your handling code here:
        new Employee().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_employeePanelJumpMouseClicked

    private void categoryPanelJumpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryPanelJumpMouseClicked
        // TODO add your handling code here:
        new Category().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_categoryPanelJumpMouseClicked

    private void logoutPanelJumpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelJumpMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutPanelJumpMouseClicked

    private void movieDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieDescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MoviePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MoviePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MoviePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MoviePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JButton addMovie;
    private javax.swing.JLabel categoryPanelJump;
    private javax.swing.JButton clearMovie;
    private javax.swing.JButton deleteMovie;
    private javax.swing.JButton editMovie;
    private javax.swing.JLabel employeePanelJump;
    private javax.swing.JLabel exitProduct;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logoutPanelJump;
    private javax.swing.JComboBox<String> movieCategory;
    private javax.swing.JTextField movieDesc;
    private javax.swing.JTextField movieID;
    private javax.swing.JTextField movieName;
    private javax.swing.JTextField moviePrice;
    private javax.swing.JTable movieTable;
    private javax.swing.JTextField movieTicketQuantity;
    // End of variables declaration//GEN-END:variables
}
